### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by nibsbin**

### CODE REVIEW

**Comment by LockstepThrowaway** [comment]
Hi Mr. Pan,
I hope you don't mind, but I couldn't find any better way to message you.

I wanted to say this framework looks really solid (I skimmed over most of it last night), but I was wondering how exactly this connects to a server/P2P? The Network Manager has all of the client-side data, and the beginnings of a connection protocol, but it never actually sends anything. 

I am more than happy to write it myself (since I can then write the server too), but I was wondering how the best way to do that might be (any info that MUST be included that I might overlook, etc), and if you had any suggestions otherwise.

Thank you for your time,
Throwaway

P.S. Sorry about your failed Kickstarter (I found this project through /r/Gamedev).

**Comment by nibsbin** [comment]
Thanks for your sympathy. Our project unfortunately got cancelled before I
got to multiplayer networking so you'll need to write it yourself.

The system's currently set up for receiving information from 1 entity (i.e.
a server) but P2P would also work if you make sure that you get a packet
from every player before creating a frame and sending it to FrameManager.

With a server, all that needs to be done is getting packets into
FastList<byte> ReceivedBytes. I'm about to update LSF with some updated
NetworkManager logic so this applies to the update: In the switch
statement, add a case for SendState.Network and create a list of bytes. For
every command in OutCommands, call Command.serialized and add the byte[] to
the list of bytes. Then send that to the server.

The server doesn't need to deserialize the commands - it just needs to
relay it to everyone. It sends all the bytes it received that frame to all
the clients, along with a BitConverter.GetBytes (int
LockstepManager.FrameCount) in the beginning to identify which frame the
data is meant for.

Note that framerate is set to 32fps but human reaction time is at a much
lower frequency which is why NetworkingIterationSpread was implemented.
With a value of 2, the NetworkManager will send and expect data every 2
frames. With a value of 3, it will send/expect data every 3 frames.

On Thu, Jul 30, 2015 at 8:27 AM, LockstepThrowaway <notifications@github.com

**Comment by LockstepThrowaway** [comment]
Thanks for the tips!

I'm still fairly new to programming, but with enough experience that I've written my own (rather poor) netcode from scratch. I do intend to have the server deserialize any data it receives (for the sake of being authoritative), which also allows me to use the server for more than just relaying. 

As for the framerate, I did notice that, though the simulate and visualize are different (unless you meant that visualize is fixed to 32 FPS). I assume you mean that the lockstep tries to wait for 32 frames per second.

With regards to simulation, I wanted to ask a few things:
1. The controllable agents have very strange behaviour - it _looks_ as though they go through walls, but I have seen them path around it, so I'm assuming they're just too fast for me to notice. However, when they reach their destination, they keep swarming around it, and often times don't stop. If you have any suggestions for it, I'd be interested.
2. I've encountered several IndexOutOfRange issues - I've done my best to fix them, but they've tended to have strange side effects. With the build I downloaded last night, simply selecting all 256 units and moving them is enough to cause it (I've also tried lowering it to 254 spawned units, but that didn't fix it). Again, any suggestions are welcome.

Further, in my previous project, I added headers to the sent/received data in order to route it to the correct function to deal with it - could I still do that, and just make sure that the FastList<byte> ReceivedBytes gets sent as well? Also, what exactly is stored in the bytes list?

Thank you for making this open source and taking the time to answer my question, and I hope you don't mind if I post any other questions I have here. :D

**Comment by nibsbin** [comment]
Simulate () is run in FixedUpdate in Unity and Visualize is run in Update.
FixedUpdate's framerate is determined by Time.fixedDeltaTime. Update's
framerate is the one you see when you open the stats window in the editor
and objects get rendered every Update frame which is why positions are only
communicated to Unity in Visualize.
1. I think this is a problem revolves around how collisions are handled.
   I'll look more into this but in the meantime, does lowering the units'
   movement speed help with this problem? I think I let a problem with
   serialization go unchecked which gave units insane movement speed.
2. I'm actually not sure what's happening here. If the units are moving too
   fast, they could be going outside of the partition or grid which leads to
   issues (haven't put anything solid in to deal with going outside of the
   bounds yet).
   Increasing Partition.Count and GridManager.NodeCount will increase the
   bounds of the game.

For sending data, you can do anything as long as you get the bytes from
Command.Serialized into Command.Reconstruct to reconstruct the command and
use it for simulation.

You're welcome and thanks for the encouragement. I'm happy to answer
questions and questions help me find the weaknesses of the project so ask
away please!

**Comment by nibsbin** [comment]
P.S. In regards to 2., can you send me the entire error log? Thanks.

**Comment by LockstepThrowaway** [comment]
Happy to provide (both encouragement and error logs)! 
<code>
IndexOutOfRangeException: Array index is out of range.
Lockstep.FastList`1[Lockstep.Vector2d].get_Item (Int32 index) (at Assets/Lockstep-Framework-master/Core/Utility/FastList.cs:150)
Move.Simulate () (at Assets/Lockstep-Framework-master/Core/Game/Abilities/Essential/Move/Move.cs:156)
Lockstep.LSAgent.Simulate () (at Assets/Lockstep-Framework-master/Core/Game/Agents/LSAgent.cs:50)
Lockstep.AgentController.SimulateLocal () (at Assets/Lockstep-Framework-master/Core/Game/Agents/AgentController.cs:94)
Lockstep.AgentController.Simulate () (at Assets/Lockstep-Framework-master/Core/Game/Agents/AgentController.cs:56)
Lockstep.LockstepManager.Simulate () (at Assets/Lockstep-Framework-master/Core/Game/Managers/LockstepManager.cs:60)
TestManager.FixedUpdate () (at Assets/Lockstep-Framework-master/Example/TestManager.cs:57)
</code>

This is the error I was getting.

As for the movement speed, to be quite honest: I'm not sure what field to actually change for that,

**Comment by nibsbin** [comment]
Thanks for the log. I've pushed the most recent of LSF that (hopefully)
fixes this issue. It's in the develop branch because there are still some
unfinished things but it compiles without errors so should be no problem.

The Move ability is an attached component to TestObject. You can find it by
clicking on TestObject and changing the Speed value.

On Thu, Jul 30, 2015 at 2:28 PM, LockstepThrowaway <notifications@github.com

**Comment by LockstepThrowaway** [comment]
Looking at the test objects, they have some very strange values: 13107 as a radius, for example ... what units is that in? For comparison, Unity says their scale is 0.4 (on all axis). Their speed is 48 and their "Veloity Magnitutde" is 50944. 

I'm not sure, but these numbers don't quite sound right. Any ideas on where how to fix them?

**Comment by nibsbin** [comment]
Ah, right. Fixed-point numbers are stored in longs and aren't meant for
human's eyes. Before runtime, FP numbers are converted to doubles to
present to the user and when modified, the double is converted back to a FP
number and serialized. 13107 is the long value the radius is stored as, but
when converted to a double then to a string, it's .2. It's just one of the
annoying things about integrating deterministic math into Unity.

Out of runtime, you should be able to set all the exposed values normally.

On Thu, Jul 30, 2015 at 3:05 PM, LockstepThrowaway <notifications@github.com

**Comment by LockstepThrowaway** [comment]
So, I feel pretty stupid for just now finding the very obvious TestObject object. I've set their speed to 5 (from 48) and turn rate to 3 (from 16) and their behaviour is much better. It also helped confirm that they do in fact go through the walls, but then get stuck inside. My guess is that the other units are pushing them in, and they can't get out. Any place that has 4 walls side by side as the vertices of a square can cause this issue. I'd say that it won't really be an issue if you can't solve it, since a solid wall should easily fix this.

I do have a question about the way you set this up though: you have a grid with (what I'm assuming are regular square) nodes, but you also have agent and wall radii; so what is used for pathing?

**Comment by nibsbin** [comment]
Pathfinding is done with a 2D array of GridNodes. It's actually pretty
basic and nodes currently have to be manually set with GridManager.GetNode
(nodeX, nodeY).Unwalkable = true.

On Thu, Jul 30, 2015 at 3:33 PM, LockstepThrowaway <notifications@github.com

**Comment by nibsbin** [comment]
Oh, forgot to mention... there are diagnal connections which is why walls
are represented as circles. This can be changed in GridNode.GenerateNodes
by not assigning any diagnal nodes to GridNode[] Neighbors.

**Comment by LockstepThrowaway** [comment]
Is there any way to visualize the nodes on GridManager? I'm wondering what the interaction is that allows the agents to glitch through the walls?

**Comment by LockstepThrowaway** [comment]
Followup question: Why not use Unity's built-in pathing features? Is it due to it being harder to make them deterministic? Or is there some other advantage to your custom made system? (Just curious)

**Comment by nibsbin** [comment]
I'm not sure exactly how Unity's navigation works since it's very
hush-hush, but there's no way to control when the navigation is simulated
(it's not run with FixedUpdate). Even if simulation could be controlled, I
have a feeling that Unity Nav's extensive use of floats would lead to some
nasty desyncs.

Unity Nav had an entire team working on it which gives it some more
features (i.e. Navmesh, height factor, sexy editor graphics). With that
said, there are a few advantages to my jury-rigged pathfinding and
navigation.
-Deterministic :P
-It's about 4x as fast (512 individually navigating units is no problem for
LSF)
-Uses a grid which gives you more control over the pathfinding.
-There's source-code access so you can change anything you don't like

**Comment by LockstepThrowaway** [comment]
Pardon my pestering, but I've moved the camera down (to 10 units above the XZ plane) and I've noticed that with my current settings (speed of 5, turn rate of 3), the agents will turn while moving, and will sometimes finish turning after they've arrived at their destination. 

This isn't a major issue, but it might be important to consider for future proofing.

**Comment by LockstepThrowaway** [comment]
And about your system, should node count be increased linearly, or quadratically? And building on that, if I were to use a mesh as my terrain, what would be the best method to make it properly line up with your grids?

And out of curiosity, does this current system support different ground heights (such as StarCraft 2)?

**Comment by LockstepThrowaway** [comment]
Nevermind on the nodecount question - I should probably double check through the code before asking all these questions. I found the answer.

**Comment by nibsbin** [comment]
The Turn behavior mainly shows how to get objects to turn incrementally and
smoothly. It's probably best to write a new behavior for your specific
needs.

As for height testing, that can be implemented pretty easily by just
setting transform.position.y to whatever position you want it to be on, on
the Y-axis. Here's an example.

On Thu, Jul 30, 2015 at 5:24 PM, LockstepThrowaway <notifications@github.com

**Comment by LockstepThrowaway** [comment]
That example is just a quote of my last comment. However, I've since had the idea to make the grid 3D, and use it like that somehow ... give it a vertical height of +1 for each "floor" ... though I'm not sure if your current path finding will easily be adapted to that.

**Comment by nibsbin** [comment]
Ah, looks like the files didn't attach. Good luck with your idea.

On Thu, Jul 30, 2015 at 6:11 PM, LockstepThrowaway <notifications@github.com

**Comment by LockstepThrowaway** [comment]
Thanks!

I won't be able to work on this for a bit over a week, though I'll definitely let you know about any progress (and bugs) I find.

Thanks again for sharing, and good luck in the future! :D

**Pull request merged**
